Repository dcos/dcos-core-cli, pull requests merged in 2018-08, with the labels that each got.

#12 adding pods to the possible filters for deployments
  python/lib/dcos/dcos/marathon.py
Labels: 1.10, 1.11, 1.12

#19 Fixes table printer when rendering empty data
  python/lib/dcoscli/dcoscli/tables.py
Labels: 1.10, 1.11, 1.12, needs-backport

#22 0.5 Fixes table printer when rendering empty data
  cli/dcoscli/tables.py
Labels: 1.10

#21 0.6 Fixes table printer when rendering empty data
  cli/dcoscli/tables.py
Labels: 1.11
